const page=document.getElementById('page');
let S={user:null,profile:null,partner:null,products:[],view:'dashboard',admin:false};

(async function init(){
  try{
    const base=await bootstrap();S={...S,...base};S.admin=await isAdmin();S.products=await loadAllProducts();
    const initials=(S.profile?.full_name||S.user.email||'EP').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
    avatar.textContent=initials;miniName.textContent=S.profile?.full_name||S.user.email;miniCompany.textContent=S.profile?.company_name||S.profile?.company_type||'Partener eBlat';
    bindShell();await showView(new URLSearchParams(location.search).get('view')||'dashboard');
  }catch(e){if(e.message!=='AUTH_REQUIRED'){page.innerHTML=`<div class="empty">Eroare la încărcare: ${esc(e.message)}</div>`}}
})();

function bindShell(){
  document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
  logoutTop.onclick=signOut;newProjectTop.onclick=openNewProject;
  globalSearch.addEventListener('keydown',e=>{if(e.key==='Enter'){showView('materials',globalSearch.value.trim())}});
}
function setActive(view){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));S.view=view;history.replaceState({},'',`app.html?view=${view}`)}
async function showView(view,q=''){setActive(view);page.innerHTML='<div class="empty">Se încarcă…</div>';const map={dashboard:renderDashboard,projects:renderProjects,materials:()=>renderMaterials(q),samples:renderSamples,quotes:renderQuotes,wallet:renderWallet,moodboards:renderMoodboards,profile:renderProfile};await(map[view]||renderDashboard)()}

async function renderDashboard(){
  const [{data:projects},{count:samples},{count:quotes},{count:favs},{data:ledger},{data:notifs}]=await Promise.all([
    sb.from('eblat_projects').select('*').order('created_at',{ascending:false}).limit(5),
    sb.from('eblat_samples').select('*',{count:'exact',head:true}),
    sb.from('eblat_quotes').select('*',{count:'exact',head:true}),
    sb.from('eblat_favorites').select('*',{count:'exact',head:true}),
    sb.from('eblat_wallet_ledger').select('*').order('created_at',{ascending:false}),
    sb.from('eblat_notifications').select('*').is('read_at',null).order('created_at',{ascending:false}).limit(5)
  ]);
  const {count:projectCount}=await sb.from('eblat_projects').select('*',{count:'exact',head:true});
  const pending=(ledger||[]).filter(x=>x.kind==='pending').reduce((a,x)=>a+Number(x.amount),0),earned=(ledger||[]).filter(x=>x.kind==='earned').reduce((a,x)=>a+Number(x.amount),0);
  const rate=Math.round(Number(S.partner?.commission_rate||.05)*100);const partnerStatus=S.partner?.status||'pending';
  page.innerHTML=`<div class="page-head"><div><div class="eyebrow">eBlat PRO V3 · live</div><h1>Bună, ${esc((S.profile?.full_name||'partener').split(' ')[0])}.</h1><p>Proiecte, materiale, mostre și comisioane salvate online.</p></div><button class="btn dark" id="dashNew">+ Proiect nou</button></div>
  ${partnerStatus!=='active'?`<div class="notice">Contul comercial este <b>${esc(partnerStatus)}</b>. Workspace-ul funcționează, iar condițiile comerciale se activează din Admin. Rata configurată: ${rate}%.</div>`:''}
  <div class="stats"><div class="stat"><div class="ico">▧</div><div><b>${projectCount||0}</b><span>proiecte</span></div></div><div class="stat"><div class="ico">▤</div><div><b>${samples||0}</b><span>mostre solicitate</span></div></div><div class="stat"><div class="ico">▣</div><div><b>${quotes||0}</b><span>oferte</span></div></div><div class="stat"><div class="ico">♡</div><div><b>${favs||0}</b><span>favorite</span></div></div></div>
  <div class="grid2"><section class="panel"><div class="section-head" style="margin-top:0"><div><h2>Partner Wallet</h2><p>Comisioane generate din oferte aprobate.</p></div><button class="btn sm" data-go="wallet">Vezi wallet</button></div><div class="wallet-cards"><div class="wallet-card"><small>Disponibil</small><b>${money(earned)}</b></div><div class="wallet-card"><small>În așteptare</small><b>${money(pending)}</b></div><div class="wallet-card"><small>Nivel</small><b>${esc(S.partner?.tier||'partner')}</b></div></div></section><section class="panel"><div class="section-head" style="margin-top:0"><div><h2>Notificări</h2><p>Statusuri trimise de eBlat.</p></div></div>${(notifs||[]).length?(notifs||[]).map(n=>`<div style="padding:9px 0;border-bottom:1px solid var(--line)"><b class="small">${esc(n.title)}</b><div class="small muted">${esc(n.body||'')}</div></div>`).join(''):'<div class="muted small">Nu ai notificări noi.</div>'}</section></div>
  <div class="section-head"><div><h2>Proiecte recente</h2><p>Statusul lucrărilor tale.</p></div><button class="btn sm" data-go="projects">Toate proiectele</button></div><div class="cards">${(projects||[]).map(projectCard).join('')||'<div class="empty">Creează primul proiect eBlat PRO.</div>'}</div>
  <div class="section-head"><div><h2>Materiale recomandate</h2><p>Catalog sincronizat în Supabase: ${S.products.length} produse.</p></div><button class="btn sm" data-go="materials">Catalog</button></div><div class="products">${S.products.slice(0,4).map(productCard).join('')}</div>`;
  dashNew.onclick=openNewProject;page.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));bindProjectCards();bindProducts(page);
}
function projectCard(p){return `<article class="project-card" data-project="${p.id}"><span class="tag ${statusClass(p.status)}">${statusLabel(p.status)}</span><h3 style="margin-top:10px">${esc(p.name)}</h3><div class="small muted">${esc(p.client_name||'Fără client')} · ${esc(p.city||'—')}</div>${timeline(p.status)}<div class="small"><b>${money(p.estimated_value)}</b> valoare estimată</div><div class="actions"><button class="btn sm project-open">Deschide</button><button class="btn sm quote-project">Ofertă</button></div></article>`}
function bindProjectCards(){page.querySelectorAll('[data-project]').forEach(c=>{const id=c.dataset.project;c.querySelector('.project-open').onclick=()=>openProject(id);c.querySelector('.quote-project').onclick=()=>openQuote(null,id)})}

async function renderProjects(){const {data}=await sb.from('eblat_projects').select('*').order('created_at',{ascending:false});page.innerHTML=`<div class="page-head"><div><div class="eyebrow">Workspace</div><h1>Proiecte.</h1><p>Fișiere, materiale, oferte și status într-un singur dosar.</p></div><button class="btn dark" id="pNew">+ Proiect nou</button></div><div class="cards">${(data||[]).map(projectCard).join('')||'<div class="empty">Nu ai proiecte încă.</div>'}</div>`;pNew.onclick=openNewProject;bindProjectCards()}
async function openNewProject(){const o=openModal(`<div class="modal-head"><h2>Proiect nou</h2><button class="close">×</button></div><form id="projectForm" class="form"><div class="field full"><label>Nume proiect</label><input name="name" required placeholder="ex. Vila Pipera — Bucătărie"></div><div class="field"><label>Client</label><input name="client"></div><div class="field"><label>Oraș</label><input name="city" value="București"></div><div class="field"><label>Tip proiect</label><select name="type"><option>Bucătărie</option><option>Baie</option><option>Comercial</option><option>Mobilier / showroom</option></select></div><div class="field"><label>Valoare estimată</label><input name="value" type="number" value="0"></div><div class="field full"><label>Detalii</label><textarea name="description"></textarea></div><div class="field full"><label>Schiță / randare / PDF</label><input name="file" type="file" accept="image/*,.pdf"></div><div class="field full"><button class="btn dark" type="submit">Salvează proiectul →</button></div></form>`);o.querySelector('.close').onclick=closeModal;o.querySelector('#projectForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const {data,error}=await sb.from('eblat_projects').insert({owner_id:S.user.id,name:f.get('name'),client_name:f.get('client'),city:f.get('city'),project_type:f.get('type'),estimated_value:Number(f.get('value')||0),description:f.get('description')}).select().single();if(error)return toast(error.message);try{await uploadProjectFile(S.user.id,data.id,f.get('file')?.size?f.get('file'):null)}catch(x){toast('Proiect salvat; fișierul nu s-a putut încărca: '+x.message)}closeModal();toast('Proiect salvat online');showView('projects')}}
async function openProject(id){const [{data:p},{data:mats},{data:files},{data:quotes}]=await Promise.all([sb.from('eblat_projects').select('*').eq('id',id).single(),sb.from('eblat_project_materials').select('*').eq('project_id',id),sb.from('eblat_project_files').select('*').eq('project_id',id).order('created_at',{ascending:false}),sb.from('eblat_quotes').select('*').eq('project_id',id).order('created_at',{ascending:false})]);const fileLinks=[];for(const f of files||[])fileLinks.push(`<a class="btn sm" target="_blank" href="${await signedUrl(f.storage_path)}">${esc(f.file_name)}</a>`);const o=openModal(`<div class="modal-head"><h2>${esc(p.name)}</h2><button class="close">×</button></div><div class="tag ${statusClass(p.status)}">${statusLabel(p.status)}</div>${timeline(p.status)}<p class="muted small">${esc(p.client_name||'')} · ${esc(p.city||'')} · ${esc(p.project_type||'')}</p><div class="section-head"><div><h2>Materiale</h2></div></div>${(mats||[]).map(x=>`<div class="panel" style="margin-bottom:7px"><b class="small">${esc(x.product_title)}</b><div class="small muted">${esc(x.product_brand||'')} · ${x.quantity} unit.</div></div>`).join('')||'<div class="muted small">Niciun material adăugat.</div>'}<div class="section-head"><div><h2>Fișiere</h2></div></div><div class="actions">${fileLinks.join('')||'<span class="muted small">Niciun fișier.</span>'}</div><div class="section-head"><div><h2>Oferte</h2></div></div>${(quotes||[]).map(q=>`<div class="panel" style="margin-bottom:7px"><b>${esc(q.quote_number)}</b> · ${money(q.total)} <span class="tag ${statusClass(q.status)}">${esc(q.status)}</span></div>`).join('')||'<div class="muted small">Nicio ofertă.</div>'}<div class="actions"><button class="btn dark" id="detailQuote">Creează ofertă</button><button class="btn" id="detailMaterial">Alege materiale</button></div>`);o.querySelector('.close').onclick=closeModal;o.querySelector('#detailQuote').onclick=()=>{closeModal();openQuote(null,id)};o.querySelector('#detailMaterial').onclick=()=>{closeModal();showView('materials')}}

function productCard(p,favs=new Set()){return `<article class="product" data-product="${p.product_id}"><button class="heart ${favs.has(p.product_id)?'active':''}" title="Favorite">${favs.has(p.product_id)?'♥':'♡'}</button><img loading="lazy" src="${esc(productImg(p))}" alt="${esc(p.title)}"><div class="product-body"><h3>${esc(p.title)}</h3><div class="small muted">${esc(p.brand||'')} · ${esc(p.material||'')}</div><div class="price">${esc(p.price_text||money(p.price))}</div><div class="product-actions"><button class="sample">Mostră</button><button class="project">+ Proiect</button><button class="mood">Moodboard</button><button class="dark quote">Ofertă</button></div></div></article>`}
async function renderMaterials(initial=''){const [{data:favRows}]=await Promise.all([sb.from('eblat_favorites').select('product_id')]);const favs=new Set((favRows||[]).map(x=>x.product_id));page.innerHTML=`<div class="page-head"><div><div class="eyebrow">Catalog sincronizat</div><h1>Materiale.</h1><p>${S.products.length} produse reale importate în baza eBlat.</p></div></div><div class="toolbar"><input id="mq" placeholder="Caută material, brand..." value="${esc(initial)}"><select id="mmat"><option value="">Toate materialele</option>${[...new Set(S.products.map(x=>x.material).filter(Boolean))].sort().map(x=>`<option>${esc(x)}</option>`).join('')}</select><select id="mbrand"><option value="">Toate brandurile</option>${[...new Set(S.products.map(x=>x.brand).filter(Boolean))].sort().map(x=>`<option>${esc(x)}</option>`).join('')}</select><select id="msort"><option value="name">A–Z</option><option value="low">Preț ↑</option><option value="high">Preț ↓</option></select></div><div class="small muted" id="mcount"></div><div class="products" id="productGrid" style="margin-top:12px"></div>`;let limit=40;function draw(){let arr=S.products.filter(p=>(!mq.value||`${p.title} ${p.brand} ${p.material}`.toLowerCase().includes(mq.value.toLowerCase()))&&(!mmat.value||p.material===mmat.value)&&(!mbrand.value||p.brand===mbrand.value));if(msort.value==='low')arr.sort((a,b)=>Number(a.price)-Number(b.price));else if(msort.value==='high')arr.sort((a,b)=>Number(b.price)-Number(a.price));else arr.sort((a,b)=>a.title.localeCompare(b.title,'ro'));mcount.textContent=`${arr.length} rezultate`;productGrid.innerHTML=arr.slice(0,limit).map(p=>productCard(p,favs)).join('')||'<div class="empty">Niciun rezultat.</div>';bindProducts(productGrid,favs)}[mq,mmat,mbrand,msort].forEach(x=>x.oninput=draw);draw()}
function bindProducts(root,favs=new Set()){root.querySelectorAll('[data-product]').forEach(c=>{const p=S.products.find(x=>x.product_id===Number(c.dataset.product));if(!p)return;c.querySelector('.heart').onclick=async()=>{if(favs.has(p.product_id)){await sb.from('eblat_favorites').delete().eq('product_id',p.product_id);favs.delete(p.product_id);c.querySelector('.heart').classList.remove('active');c.querySelector('.heart').textContent='♡'}else{const {error}=await sb.from('eblat_favorites').insert({user_id:S.user.id,product_id:p.product_id,product_title:p.title});if(error)return toast(error.message);favs.add(p.product_id);c.querySelector('.heart').classList.add('active');c.querySelector('.heart').textContent='♥'}toast('Favorite actualizate')};c.querySelector('.sample').onclick=()=>requestSample(p);c.querySelector('.project').onclick=()=>addToProject(p);c.querySelector('.quote').onclick=()=>openQuote(p);c.querySelector('.mood').onclick=()=>addToMoodboard(p)})}
async function requestSample(p){const {error}=await sb.from('eblat_samples').insert({user_id:S.user.id,product_id:p.product_id,product_title:p.title,status:'requested'});toast(error?error.message:'Mostră solicitată')}
async function addToProject(p){const {data:projects}=await sb.from('eblat_projects').select('id,name').order('created_at',{ascending:false});if(!projects?.length){toast('Creează mai întâi un proiect');return openNewProject()}const o=openModal(`<div class="modal-head"><h2>Adaugă la proiect</h2><button class="close">×</button></div><form id="addMat" class="form"><div class="field full"><label>Material</label><input disabled value="${esc(p.title)}"></div><div class="field full"><label>Proiect</label><select name="project">${projects.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>Cantitate / mp estimat</label><input name="qty" type="number" step="0.1" value="1"></div><div class="field"><label>Notițe</label><input name="notes"></div><div class="field full"><button class="btn dark">Adaugă →</button></div></form>`);o.querySelector('.close').onclick=closeModal;o.querySelector('#addMat').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await sb.from('eblat_project_materials').insert({project_id:f.get('project'),product_id:p.product_id,product_title:p.title,product_brand:p.brand,product_price:p.price,quantity:Number(f.get('qty')||1),notes:f.get('notes')});if(error)return toast(error.message);closeModal();toast('Material adăugat la proiect')}}
async function openQuote(product=null,projectId=null){const [{data:projects}]=await Promise.all([sb.from('eblat_projects').select('id,name').order('created_at',{ascending:false})]);const p=product||S.products[0];if(!p)return toast('Catalog indisponibil');const rate=Number(S.partner?.commission_rate||.05);const o=openModal(`<div class="modal-head"><h2>Ofertare asistată</h2><button class="close">×</button></div><form id="quoteForm" class="form"><div class="field full"><label>Proiect</label><select name="project"><option value="">Fără proiect</option>${(projects||[]).map(x=>`<option value="${x.id}" ${x.id===projectId?'selected':''}>${esc(x.name)}</option>`).join('')}</select></div><div class="field full"><label>Material</label><select name="product">${S.products.map(x=>`<option value="${x.product_id}" ${x.product_id===p.product_id?'selected':''}>${esc(x.title)} — ${esc(x.price_text||'')}</option>`).join('')}</select></div><div class="field"><label>Suprafață estimată (mp)</label><input name="area" type="number" step="0.01" min="0.1" value="3.2"></div><div class="field"><label>Decupaje</label><input name="cuts" type="number" min="0" value="2"></div><div class="field"><label>Montaj</label><select name="install"><option value="1">Inclus</option><option value="0">Fără</option></select></div><div class="field"><label>Comision partener</label><input disabled value="${Math.round(rate*100)}% · calculat server-side"></div><div class="field full"><label>Notițe</label><textarea name="notes"></textarea></div><div class="field full"><div class="notice" id="quotePreview"></div></div><div class="field full"><button class="btn dark">Trimite spre analiză →</button></div></form>`);o.querySelector('.close').onclick=closeModal;const f=o.querySelector('#quoteForm');function preview(){const x=S.products.find(z=>z.product_id===Number(f.product.value))||p,a=Number(f.area.value||0),cuts=Number(f.cuts.value||0),install=f.install.value==='1'?850:0,total=a*Number(x.price||0)+cuts*250+install;quotePreview.innerHTML=`Estimare: <b>${money(total)}</b> · comision potențial ${money(total*rate)}. Prețul final se confirmă de eBlat.`}[f.product,f.area,f.cuts,f.install].forEach(x=>x.oninput=preview);preview();f.onsubmit=async e=>{e.preventDefault();const {data,error}=await sb.rpc('eblat_create_quote',{p_project_id:f.project.value||null,p_product_id:Number(f.product.value),p_area:Number(f.area.value),p_cuts:Number(f.cuts.value||0),p_install:f.install.value==='1',p_notes:f.notes.value||null});if(error)return toast(error.message);closeModal();toast('Oferta '+data+' a fost trimisă spre analiză');showView('quotes')}}

async function renderSamples(){const {data}=await sb.from('eblat_samples').select('*').order('created_at',{ascending:false});page.innerHTML=`<div class="page-head"><div><div class="eyebrow">Materiale reale</div><h1>Mostre.</h1><p>Urmărește cererile trimise către eBlat.</p></div></div>${(data||[]).length?`<table class="table"><thead><tr><th>Material</th><th>Status</th><th>Data</th></tr></thead><tbody>${data.map(x=>`<tr><td><b>${esc(x.product_title)}</b></td><td><span class="tag ${statusClass(x.status)}">${esc(x.status)}</span></td><td>${new Date(x.created_at).toLocaleDateString('ro-RO')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Nu ai cereri de mostre.</div>'}`}
async function renderQuotes(){const {data}=await sb.from('eblat_quotes').select('*').order('created_at',{ascending:false});page.innerHTML=`<div class="page-head"><div><div class="eyebrow">Oferte server-side</div><h1>Oferte.</h1><p>Comisionul este calculat de backend, nu de browser.</p></div><button class="btn dark" id="qNew">+ Ofertă nouă</button></div><div class="cards">${(data||[]).map(q=>`<article class="quote-card"><span class="tag ${statusClass(q.status)}">${esc(q.status)}</span><h3 style="margin-top:9px">${esc(q.quote_number)}</h3><div class="small muted">${new Date(q.created_at).toLocaleDateString('ro-RO')}</div><div style="font-size:24px;font-weight:800;margin-top:12px">${money(q.total)}</div><div class="small">Comision: <b>${money(q.partner_commission)}</b></div><div class="actions"><button class="btn sm print-quote" data-id="${q.id}">Print/PDF</button></div></article>`).join('')||'<div class="empty">Nu ai oferte încă.</div>'}</div>`;qNew.onclick=()=>openQuote();page.querySelectorAll('.print-quote').forEach(b=>b.onclick=()=>printQuote(b.dataset.id))}
async function printQuote(id){const [{data:q},{data:items}]=await Promise.all([sb.from('eblat_quotes').select('*').eq('id',id).single(),sb.from('eblat_quote_items').select('*').eq('quote_id',id)]);const brand=S.profile?.brand_name||S.profile?.company_name||'Partener eBlat PRO';const w=window.open('','_blank');w.document.write(`<html><head><title>${esc(q.quote_number)}</title><style>body{font-family:Arial;padding:48px;color:#222}.head{display:flex;justify-content:space-between;border-bottom:2px solid #111;padding-bottom:20px}.total{font-size:34px;font-weight:bold;margin:25px 0}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid #ddd;text-align:left}.foot{margin-top:35px;color:#777;font-size:12px}</style></head><body><div class="head"><div><h1>${esc(brand)}</h1><div>Ofertă white-label</div></div><div><b>${esc(q.quote_number)}</b><br>${new Date(q.created_at).toLocaleDateString('ro-RO')}</div></div><div class="total">${money(q.total)}</div><table><tr><th>Material / serviciu</th><th>Cant.</th><th>Preț</th></tr>${(items||[]).map(i=>`<tr><td>${esc(i.title)}</td><td>${i.quantity}</td><td>${money(i.line_total)}</td></tr>`).join('')}<tr><td>Transport / montaj</td><td>—</td><td>${money(q.install_amount)}</td></tr></table><div class="foot">Ofertă orientativă. Validarea tehnică și prețul final se confirmă după măsurători și verificarea condițiilor proiectului. Furnizare tehnică prin eBlat.</div><script>window.print()<\/script></body></html>`);w.document.close()}

async function renderWallet(){const {data}=await sb.from('eblat_wallet_ledger').select('*').order('created_at',{ascending:false});const rows=data||[],earned=rows.filter(x=>x.kind==='earned').reduce((a,x)=>a+Number(x.amount),0),pending=rows.filter(x=>x.kind==='pending').reduce((a,x)=>a+Number(x.amount),0),paid=rows.filter(x=>x.kind==='paid').reduce((a,x)=>a+Number(x.amount),0);page.innerHTML=`<div class="page-head"><div><div class="eyebrow">Partner Wallet</div><h1>Comisioane.</h1><p>Ledger real generat de ofertele aprobate.</p></div></div><section class="wallet-hero"><div><div class="eyebrow" style="color:#d8bfa5">Disponibil</div><h2>Comision câștigat</h2><div class="amount">${money(earned)}</div></div><div class="tag">${Math.round(Number(S.partner?.commission_rate||.05)*100)}% · ${esc(S.partner?.tier||'partner')}</div></section><div class="wallet-cards"><div class="wallet-card"><small>În așteptare</small><b>${money(pending)}</b></div><div class="wallet-card"><small>Plătit</small><b>${money(paid)}</b></div><div class="wallet-card"><small>Total generat</small><b>${money(earned+pending+paid)}</b></div></div><div class="section-head"><div><h2>Istoric</h2></div></div>${rows.length?`<table class="table"><thead><tr><th>Tip</th><th>Descriere</th><th>Sumă</th><th>Data</th></tr></thead><tbody>${rows.map(x=>`<tr><td><span class="tag ${statusClass(x.kind)}">${esc(x.kind)}</span></td><td>${esc(x.description||'')}</td><td><b>${money(x.amount)}</b></td><td>${new Date(x.created_at).toLocaleDateString('ro-RO')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Comisioanele apar aici după aprobarea unei oferte.</div>'}`}

async function renderMoodboards(){const {data}=await sb.from('eblat_moodboards').select('*').order('created_at',{ascending:false});page.innerHTML=`<div class="page-head"><div><div class="eyebrow">Client presentation</div><h1>Moodboards.</h1><p>Creează selecții de materiale și trimite clientului un singur link.</p></div><button class="btn dark" id="mNew">+ Moodboard</button></div><div class="cards">${(data||[]).map(m=>`<article class="mood-card"><span class="tag ${m.is_public?'green':''}">${m.is_public?'Public':'Privat'}</span><h3 style="margin-top:9px">${esc(m.title)}</h3><div class="small muted">${esc(m.client_name||'')}</div><div class="actions"><button class="btn sm mood-open" data-id="${m.id}">Deschide</button>${m.is_public?`<button class="btn sm copy-share" data-token="${m.share_token}">Copiază link</button>`:''}</div></article>`).join('')||'<div class="empty">Creează primul moodboard pentru client.</div>'}</div>`;mNew.onclick=openNewMoodboard;page.querySelectorAll('.mood-open').forEach(b=>b.onclick=()=>openMoodboard(b.dataset.id));page.querySelectorAll('.copy-share').forEach(b=>b.onclick=()=>copyShare(b.dataset.token))}
async function openNewMoodboard(){const {data:projects}=await sb.from('eblat_projects').select('id,name').order('created_at',{ascending:false});const o=openModal(`<div class="modal-head"><h2>Moodboard nou</h2><button class="close">×</button></div><form id="moodForm" class="form"><div class="field full"><label>Titlu</label><input name="title" required placeholder="Selecție materiale — Vila Pipera"></div><div class="field"><label>Client</label><input name="client"></div><div class="field"><label>Proiect</label><select name="project"><option value="">Fără proiect</option>${(projects||[]).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div class="field full"><label><input type="checkbox" name="public"> Link public pentru client</label></div><div class="field full"><button class="btn dark">Creează →</button></div></form>`);o.querySelector('.close').onclick=closeModal;o.querySelector('#moodForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await sb.from('eblat_moodboards').insert({owner_id:S.user.id,title:f.get('title'),client_name:f.get('client'),project_id:f.get('project')||null,is_public:f.get('public')==='on'});if(error)return toast(error.message);closeModal();toast('Moodboard creat');showView('moodboards')}}
async function addToMoodboard(p){const {data:boards}=await sb.from('eblat_moodboards').select('id,title').order('created_at',{ascending:false});if(!boards?.length){toast('Creează întâi un moodboard');return openNewMoodboard()}const o=openModal(`<div class="modal-head"><h2>Adaugă în moodboard</h2><button class="close">×</button></div><form id="moodAdd" class="form"><div class="field full"><label>Material</label><input disabled value="${esc(p.title)}"></div><div class="field full"><label>Moodboard</label><select name="board">${boards.map(b=>`<option value="${b.id}">${esc(b.title)}</option>`).join('')}</select></div><div class="field full"><button class="btn dark">Adaugă →</button></div></form>`);o.querySelector('.close').onclick=closeModal;o.querySelector('#moodAdd').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await sb.from('eblat_moodboard_items').insert({moodboard_id:f.get('board'),product_id:p.product_id,title:p.title,image_url:productImg(p)});if(error)return toast(error.message);closeModal();toast('Adăugat în moodboard')}}
async function openMoodboard(id){const [{data:m},{data:items}]=await Promise.all([sb.from('eblat_moodboards').select('*').eq('id',id).single(),sb.from('eblat_moodboard_items').select('*').eq('moodboard_id',id).order('sort_order')]);const o=openModal(`<div class="modal-head"><h2>${esc(m.title)}</h2><button class="close">×</button></div><div class="actions"><button class="btn sm" id="togglePublic">${m.is_public?'Fă privat':'Publică link'}</button>${m.is_public?`<button class="btn sm" id="copyPublic">Copiază link client</button>`:''}</div><div class="share-grid" style="margin-top:15px;padding-bottom:0">${(items||[]).map(i=>`<article class="share-item"><img src="${esc(i.image_url||'')}" alt="${esc(i.title)}"><div class="body"><b class="small">${esc(i.title)}</b></div></article>`).join('')||'<div class="empty">Adaugă materiale din Catalog → Moodboard.</div>'}</div>`);o.querySelector('.close').onclick=closeModal;o.querySelector('#togglePublic').onclick=async()=>{const {error}=await sb.from('eblat_moodboards').update({is_public:!m.is_public}).eq('id',m.id);if(error)return toast(error.message);closeModal();toast('Vizibilitate actualizată');renderMoodboards()};if(m.is_public)o.querySelector('#copyPublic').onclick=()=>copyShare(m.share_token)}
async function copyShare(token){const url=new URL('share.html',location.href);url.search='?token='+token;await navigator.clipboard.writeText(url.href);toast('Link copiat')}

async function renderProfile(){page.innerHTML=`<div class="page-head"><div><div class="eyebrow">Cont eBlat PRO</div><h1>Profil.</h1><p>Datele white-label și informațiile companiei.</p></div></div><div class="grid2"><form class="panel form" id="profileForm"><div class="field full"><label>Nume complet</label><input name="name" value="${esc(S.profile?.full_name||'')}"></div><div class="field"><label>Companie</label><input name="company" value="${esc(S.profile?.company_name||'')}"></div><div class="field"><label>Tip activitate</label><input name="type" value="${esc(S.profile?.company_type||'')}"></div><div class="field"><label>Telefon</label><input name="phone" value="${esc(S.profile?.phone||'')}"></div><div class="field"><label>Oraș</label><input name="city" value="${esc(S.profile?.city||'')}"></div><div class="field full"><label>Nume afișat pe oferta white-label</label><input name="brand" value="${esc(S.profile?.brand_name||'')}"></div><div class="field full"><button class="btn dark">Salvează profilul</button></div></form><div class="panel"><div class="eyebrow">Condiții comerciale</div><h2 style="margin-top:8px">${esc(S.partner?.tier||'partner')}</h2><div class="wallet-cards" style="grid-template-columns:1fr 1fr"><div class="wallet-card"><small>Status</small><b style="font-size:18px">${esc(S.partner?.status||'pending')}</b></div><div class="wallet-card"><small>Comision</small><b style="font-size:18px">${Math.round(Number(S.partner?.commission_rate||.05)*100)}%</b></div></div><div class="notice">Tier-ul și comisionul nu pot fi modificate din contul partenerului. Sunt controlate de Admin și de regulile server-side.</div><button class="btn red" id="profileLogout">Ieșire din cont</button></div></div>`;profileLogout.onclick=signOut;profileForm.onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const payload={full_name:f.get('name'),company_name:f.get('company'),company_type:f.get('type'),phone:f.get('phone'),city:f.get('city'),brand_name:f.get('brand')};const {error}=await sb.from('eblat_profiles').update(payload).eq('user_id',S.user.id);if(error)return toast(error.message);S.profile={...S.profile,...payload};toast('Profil salvat')}}
