const CAT='../../catalog_culori_quartz.json';
const K={fav:'eblatV2Fav',cmp:'eblatV2Compare',proj:'eblatV2Projects',quotes:'eblatV2Quotes',partners:'eblatV2Partners'};
const read=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const money=n=>new Intl.NumberFormat('ro-RO',{style:'currency',currency:'RON',maximumFractionDigits:0}).format(Number(n||0));
const num=p=>{const s=String(p||'').replace(/[^0-9,.-]/g,'').replace(/\./g,'').replace(',','.');return Number(s)||0};
function seed(){if(!localStorage.getItem(K.proj))write(K.proj,[{id:'P-1048',name:'Vila Pipera',client:'Familia M.',city:'București',value:12400,status:'Producție',progress:4},{id:'P-1042',name:'Penthouse Herăstrău',client:'Client privat',city:'București',value:8900,status:'Măsurare',progress:3},{id:'P-1039',name:'Office Concept',client:'Studio Nord',city:'București',value:5600,status:'Ofertă',progress:1},{id:'P-1034',name:'Villa Snagov',client:'Client privat',city:'Snagov',value:17600,status:'Montaj',progress:6}]);if(!localStorage.getItem(K.partners))write(K.partners,[{id:1,name:'Atelier Forma',type:'Mobilier',stage:'Activ',value:38200},{id:2,name:'Studio Nord',type:'Design interior',stage:'Activ',value:21400},{id:3,name:'Arch Lab',type:'Arhitectură',stage:'Onboarding',value:9600},{id:4,name:'Mob Concept',type:'Mobilier',stage:'Prospect',value:0}]);}
seed();
let catalog=[];
async function loadCatalog(){if(catalog.length)return catalog;const r=await fetch(CAT);const j=await r.json();catalog=j.products||[];return catalog}
function toast(t){let x=document.querySelector('.toast');if(!x){x=document.createElement('div');x.className='toast';document.body.appendChild(x)}x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
function shell(active='dashboard'){const side=document.querySelector('[data-shell]');if(!side)return;side.innerHTML=`<aside class="side"><a class="logo" href="./">eBlat <b>OS</b></a><div class="side-label">V2 · B2B workspace</div><nav class="side-nav"><a class="${active==='dashboard'?'active':''}" href="./"><i>⌂</i>Dashboard</a><a class="${active==='materials'?'active':''}" href="materiale.html"><i>◫</i>Materiale</a><a class="${active==='compare'?'active':''}" href="compare.html"><i>⇄</i>Compară</a><a class="${active==='quote'?'active':''}" href="quote.html"><i>▣</i>Ofertare AI</a><a class="${active==='crm'?'active':''}" href="crm.html"><i>◉</i>Parteneri CRM</a><a href="../admin/"><i>⚙</i>Admin V1</a></nav><div class="side-bottom"><div class="side-user"><div class="avatar">DN</div><div><strong>eBlat PRO</strong><span>Cont demo GitHub</span></div></div></div></aside><main class="main"><header class="top"><div class="search">⌕ <input id="globalSearch" placeholder="Caută material, proiect, brand..."></div><div class="top-actions"><a class="btn hide-mobile" href="../">Site eBlat</a><a class="btn dark" href="quote.html">+ Ofertă</a></div></header><div class="content" id="page"></div></main><nav class="mobile-nav"><a href="./"><b>⌂</b>Acasă</a><a href="materiale.html"><b>◫</b>Materiale</a><a href="compare.html"><b>⇄</b>Compară</a><a href="quote.html"><b>▣</b>Ofertă</a><a href="crm.html"><b>◉</b>CRM</a></nav>`;document.getElementById('globalSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.value.trim())location.href='materiale.html?q='+encodeURIComponent(e.target.value.trim())})}
function productCard(p){const fav=read(K.fav).includes(p.id),cmp=read(K.cmp).includes(p.id);return `<article class="product"><button class="heart ${fav?'active':''}" data-fav="${p.id}">${fav?'♥':'♡'}</button><a href="material.html?id=${p.id}"><img loading="lazy" src="${p.thumbnail_url||p.master_image_url}" alt="${p.title}"></a><div class="product-body"><h3>${p.title}</h3><div class="brand">${p.brand||''} · ${p.material||''}</div><div class="price">${p.price||'La cerere'}</div><div class="product-actions"><button data-compare="${p.id}">${cmp?'✓ În comparație':'Compară'}</button><a class="dark" href="material.html?id=${p.id}">Detalii →</a></div></div></article>`}
function bindProductActions(root=document){root.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>{let a=read(K.fav);const id=Number(b.dataset.fav);a=a.includes(id)?a.filter(x=>x!==id):[...a,id];write(K.fav,a);b.classList.toggle('active');b.textContent=a.includes(id)?'♥':'♡';toast(a.includes(id)?'Adăugat la favorite':'Scos din favorite')});root.querySelectorAll('[data-compare]').forEach(b=>b.onclick=()=>{let a=read(K.cmp);const id=Number(b.dataset.compare);if(a.includes(id))a=a.filter(x=>x!==id);else if(a.length<3)a=[...a,id];else return toast('Poți compara maximum 3 materiale');write(K.cmp,a);b.textContent=a.includes(id)?'✓ În comparație':'Compară';updateCompareFloat()});updateCompareFloat()}
function updateCompareFloat(){let f=document.querySelector('.compare-float');if(!f){f=document.createElement('button');f.className='compare-float';f.onclick=()=>location.href='compare.html';document.body.appendChild(f)}const n=read(K.cmp).length;f.textContent=`Compară (${n}) →`;f.classList.toggle('show',n>0)}
function statusClass(s){return s==='Ofertă'?'blue':s==='Măsurare'||s==='Producție'?'orange':s==='Montaj'?'':'gray'}
function progressBars(n=1){return `<div class="progress">${[1,2,3,4,5,6].map(i=>`<span class="${i<n?'done':i===n?'now':''}"></span>`).join('')}</div>`}
function parseViewParam(){return new URLSearchParams(location.search)}
